apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: demo
  labels:
    app: dummy # This allows services to find and select pods to send and forward traffic to.
spec:
  containers:
    - name: nginx
      image: nginx:latest # This will tell K8s to just find the latest NGINX image from Docker HUB.
      ports:
        - containerPort: 80 # This is the port that the NGINX process is listening to inside the container.