# There are a few different types of services in K8s. The one we are creating is a NodePort Service. 
apiVersion: v1
kind: Service
metadata:
  # Give it a label just like we do for most objects.
  labels:
    app: webserver
  # Give it a meaningful name. 
  name: webserver-service
  # Specify the namespace. Without this it just goes in default namespace.
  namespace: demo
spec:
  # NodePort: https://kubernetes.io/docs/concepts/services-networking/service/#type-nodeport
  type: NodePort
  # We have to tell the service which backend to forward traffic to. We tell it to select and pods that have the webserver label.
  selector:
    app: webserver
  ports:
  - name: 8080-8080 # You don't need this. 
    protocol: TCP
    nodePort: 31127 # This is the port that gets opened on each worker node. K8s does the work for you. 
    port: 80 # This is the port of the internal clusterip service that gets create in the background. 
    targetPort: 8080 # This is the port that the pods are listening on. We can use a named port if so desired.